### ISSUE TITLE
The pose estimation for instance object reconstruction.

### ISSUE THREAD

**Issue by yangrongkun** [GAP-LAB-CUHK-SZ/LASA#2]
Dear authors, when I read this paper, I understand that the Triplane Diffusion Model and Marching cube algorithm can generate the reconstructed object mesh, but how can we estimate the pose matrix between the generated mesh and ground truth?

Thank you.

**Comment by HaolinLiu97** [comment]
@RongkunYang Hi, we actually first need 3D object detection from the point cloud. Then, we crop the partial point cloud, put it into the canonical space, and also reconstruct the mesh in canonical space. Finally, you only need to put the mesh back according to the 3D object detection results. Now you may use the GT object poses, and the object detection codes will be cleaned later.

**Comment by yangrongkun** [comment]
OK, I understand, thank you for your enthusiastic reply.
