### ISSUE TITLE
Prerequisite for project

### ISSUE THREAD

**Issue by newzaungo3** [GAP-LAB-CUHK-SZ/LASA#4]
Hi I'm very interesting on your project. Do you have prerequisite package before running your code?

**Comment by HaolinLiu97** [comment]
@newzaungo3 Hi, you can refer to this [new repository](https://github.com/GAP-LAB-CUHK-SZ/DisCo), it contains the prerequisite that is consistent with this repository. We are currently reconstructing the code to make it user-friendly.
